name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every day

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure git
      run: |
        git config user.name 'ROLFFFX'
        git config user.email '1051268839@qq.com'

    - name: Sync fork
      run: |
        git remote add upstream https://github.com/chickblood/chickblood-website-official.git
        git fetch upstream
        git checkout main
        git merge upstream/main
        git push origin main
